In [145]:
import pandas as pd
import os
import psycopg2
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [126]:
DB_HOST = os.getenv('DB_HOST')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASS = os.getenv('DB_PASS')

In [127]:
dept_df = pd.read_csv('data/departments.csv')
dept_emp_df = pd.read_csv('data/dept_emp.csv')
dept_mgr_df = pd.read_csv('data/dept_manager.csv')
emps_df = pd.read_csv('data/employees.csv')
salary_df = pd.read_csv('data/salaries.csv')
titles_df = pd.read_csv('data/titles.csv')

In [128]:
engine = create_engine(f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:5432/HR_db')

In [129]:
dept_df.to_sql('departments',engine,index=False,if_exists='append')
print('departments')

departments

In [137]:
dept_emp_df.to_sql('dept_emp',engine,index=False,if_exists='append')
print('dept_emp')

dept_emp

In [138]:
dept_mgr_df.to_sql('dept_manager',engine,index=False,if_exists='append')
print('dept_manager')

dept_manager

In [144]:
emps_df.to_sql('employees',engine,index=False,if_exists='append')
print('employees')

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pk_employees"
DETAIL:  Key (emp_no)=(473302) already exists.

[SQL: INSERT INTO employees (emp_no, emp_title_id, birth_date, first_name, last_name, sex, hire_date) VALUES (%(emp_no)s, %(emp_title_id)s, %(birth_date)s, %(first_name)s, %(last_name)s, %(sex)s, %(hire_date)s)]
[parameters: ({'emp_no': 473302, 'emp_title_id': 's0001', 'birth_date': '7/25/1953', 'first_name': 'Hideyuki', 'last_name': 'Zallocco', 'sex': 'M', 'hire_date': '4/28/1990'}, {'emp_no': 475053, 'emp_title_id': 'e0002', 'birth_date': '11/18/1954', 'first_name': 'Byong', 'last_name': 'Delgrande', 'sex': 'F', 'hire_date': '9/7/1991'}, {'emp_no': 57444, 'emp_title_id': 'e0002', 'birth_date': '1/30/1958', 'first_name': 'Berry', 'last_name': 'Babb', 'sex': 'F', 'hire_date': '3/21/1992'}, {'emp_no': 421786, 'emp_title_id': 's0001', 'birth_date': '9/28/1957', 'first_name': 'Xiong', 'last_name': 'Verhoeff', 'sex': 'M', 'hire_date': '11/26/1987'}, {'emp_no': 282238, 'emp_title_id': 'e0003', 'birth_date': '10/28/1952', 'first_name': 'Abdelkader', 'last_name': 'Baumann', 'sex': 'F', 'hire_date': '1/18/1991'}, {'emp_no': 263976, 'emp_title_id': 'e0003', 'birth_date': '10/30/1959', 'first_name': 'Eran', 'last_name': 'Cusworth', 'sex': 'M', 'hire_date': '11/14/1986'}, {'emp_no': 273487, 'emp_title_id': 's0001', 'birth_date': '4/14/1957', 'first_name': 'Christoph', 'last_name': 'Parfitt', 'sex': 'M', 'hire_date': '6/28/1991'}, {'emp_no': 461591, 'emp_title_id': 's0002', 'birth_date': '11/17/1964', 'first_name': 'Xudong', 'last_name': 'Samarati', 'sex': 'M', 'hire_date': '11/13/1985'}  ... displaying 10 of 300024 total bound parameter sets ...  {'emp_no': 264920, 'emp_title_id': 's0001', 'birth_date': '9/22/1959', 'first_name': 'Percy', 'last_name': 'Samarati', 'sex': 'F', 'hire_date': '9/8/1994'}, {'emp_no': 464503, 'emp_title_id': 's0002', 'birth_date': '5/31/1964', 'first_name': 'Arvind', 'last_name': 'Slobodova', 'sex': 'M', 'hire_date': '11/23/1987'})]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

In [141]:
salary_df.to_sql('salaries',engine,index=False,if_exists='append')
print('salaries')

salaries

In [146]:
titles_df.to_sql('titles',engine,index=False,if_exists='append')
print('titles')

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pk_titles"
DETAIL:  Key (title_id)=(s0001) already exists.

[SQL: INSERT INTO titles (title_id, title) VALUES (%(title_id)s, %(title)s)]
[parameters: ({'title_id': 's0001', 'title': 'Staff'}, {'title_id': 's0002', 'title': 'Senior Staff'}, {'title_id': 'e0001', 'title': 'Assistant Engineer'}, {'title_id': 'e0002', 'title': 'Engineer'}, {'title_id': 'e0003', 'title': 'Senior Engineer'}, {'title_id': 'e0004', 'title': 'Technique Leader'}, {'title_id': 'm0001', 'title': 'Manager'})]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

In [147]:
dept_df.to_sql('dept_emp',engine,index=False,if_exists='append')
print('dept_emp')

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "dept_name" of relation "dept_emp" does not exist
LINE 1: INSERT INTO dept_emp (dept_no, dept_name) VALUES ('d001', 'M...
                                       ^

[SQL: INSERT INTO dept_emp (dept_no, dept_name) VALUES (%(dept_no)s, %(dept_name)s)]
[parameters: ({'dept_no': 'd001', 'dept_name': 'Marketing'}, {'dept_no': 'd002', 'dept_name': 'Finance'}, {'dept_no': 'd003', 'dept_name': 'Human Resources'}, {'dept_no': 'd004', 'dept_name': 'Production'}, {'dept_no': 'd005', 'dept_name': 'Development'}, {'dept_no': 'd006', 'dept_name': 'Quality Management'}, {'dept_no': 'd007', 'dept_name': 'Sales'}, {'dept_no': 'd008', 'dept_name': 'Research'}, {'dept_no': 'd009', 'dept_name': 'Customer Service'})]
(Background on this error at: http://sqlalche.me/e/14/f405)